//
// Created by kaaass on 2020/3/16.
//

#ifndef PICOGL_TEST_SCREEN_CONFIG_H
#define PICOGL_TEST_SCREEN_CONFIG_H

#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64
#define SCREEN_BITS_PER_PIXEL 8
#define SCREEN_LINE_BYTES_LENGTH (SCREEN_WIDTH * SCREEN_BITS_PER_PIXEL / 8)

#endif //PICOGL_TEST_SCREEN_CONFIG_H
